services:
  - type: web
    name: qc-tool
    env: python
    runtime: python
    region: oregon
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: LOG_LEVEL
        value: DEBUG
    healthCheckPath: /health
