services:
  - type: web
    name: qc-tool
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r src/backend/requirements.txt
    startCommand: python src/backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
