services:
  - type: web
    name: qc-tool
    env: python
    region: oregon
    plan: starter
    buildCommand: bash build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 600 --workers 2 'src.backend.app:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
